-- MySQL Script generated by MySQL Workbench
-- Thu May  2 22:11:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tip_zaposlenika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tip_zaposlenika` (
  `idtip_zaposlenika` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`idtip_zaposlenika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zaposlenik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zaposlenik` (
  `idzaposlenik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `lozinka` VARCHAR(255) NULL,
  `zaposlenik_tip_zaposlenika` INT NOT NULL,
  PRIMARY KEY (`idzaposlenik`),
  INDEX `fk_zaposlenik_tip_zaposlenika1_idx` (`zaposlenik_tip_zaposlenika` ASC) VISIBLE,
  CONSTRAINT `fk_zaposlenik_tip_zaposlenika1`
    FOREIGN KEY (`zaposlenik_tip_zaposlenika`)
    REFERENCES `mydb`.`tip_zaposlenika` (`idtip_zaposlenika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mjesecni_raspored`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mjesecni_raspored` (
  `idmjesecni_raspored` INT NOT NULL,
  `datum_pocetka` DATE NULL,
  `datum_zavrsetka` DATE NULL,
  PRIMARY KEY (`idmjesecni_raspored`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`soba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`soba` (
  `idsoba` INT NOT NULL AUTO_INCREMENT,
  `broj_sobe` INT NULL,
  `broj_kreveta` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idsoba`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fakultet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fakultet` (
  `idfakultet` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(100) NULL,
  `adresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idfakultet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `idstudent` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  `postanski_broj` VARCHAR(45) NULL,
  `spol` VARCHAR(45) NULL,
  `datum_rodjenja` DATE NULL,
  `student_soba` INT NOT NULL,
  `fakultet_idfakultet` INT NOT NULL,
  PRIMARY KEY (`idstudent`),
  INDEX `fk_student_soba1_idx` (`student_soba` ASC) VISIBLE,
  INDEX `fk_student_fakultet1_idx` (`fakultet_idfakultet` ASC) VISIBLE,
  CONSTRAINT `fk_student_soba1`
    FOREIGN KEY (`student_soba`)
    REFERENCES `mydb`.`soba` (`idsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_fakultet1`
    FOREIGN KEY (`fakultet_idfakultet`)
    REFERENCES `mydb`.`fakultet` (`idfakultet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`racun` (
  `idracun` INT NOT NULL AUTO_INCREMENT,
  `datum_vrijeme_racuna` VARCHAR(45) NULL,
  `ukupna_cijena` DOUBLE NULL,
  `nacin_placanja` VARCHAR(45) NULL,
  `racun_student` INT NOT NULL,
  `zaposlenik_idzaposlenik` INT NOT NULL,
  PRIMARY KEY (`idracun`),
  INDEX `fk_racun_student1_idx` (`racun_student` ASC) VISIBLE,
  INDEX `fk_racun_zaposlenik1_idx` (`zaposlenik_idzaposlenik` ASC) VISIBLE,
  CONSTRAINT `fk_racun_student1`
    FOREIGN KEY (`racun_student`)
    REFERENCES `mydb`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_racun_zaposlenik1`
    FOREIGN KEY (`zaposlenik_idzaposlenik`)
    REFERENCES `mydb`.`zaposlenik` (`idzaposlenik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kvar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kvar` (
  `idkvar` INT NOT NULL AUTO_INCREMENT,
  `opis` TEXT NULL,
  `datum_prijave` DATE NULL,
  `kvar_soba` INT NOT NULL,
  `kvar_student` INT NOT NULL,
  `kvar_zaposlenik` INT NOT NULL,
  PRIMARY KEY (`idkvar`),
  INDEX `fk_kvar_soba1_idx` (`kvar_soba` ASC) VISIBLE,
  INDEX `fk_kvar_student1_idx` (`kvar_student` ASC) VISIBLE,
  INDEX `fk_kvar_zaposlenik1_idx` (`kvar_zaposlenik` ASC) VISIBLE,
  CONSTRAINT `fk_kvar_soba1`
    FOREIGN KEY (`kvar_soba`)
    REFERENCES `mydb`.`soba` (`idsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kvar_student1`
    FOREIGN KEY (`kvar_student`)
    REFERENCES `mydb`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kvar_zaposlenik1`
    FOREIGN KEY (`kvar_zaposlenik`)
    REFERENCES `mydb`.`zaposlenik` (`idzaposlenik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`otklonjeni_kvar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`otklonjeni_kvar` (
  `idotklonjeni_kvar` INT NOT NULL AUTO_INCREMENT,
  `datum` VARCHAR(45) NULL,
  `otklonjeni_kvar_kvar` INT NOT NULL,
  `otklonjeni_kvar_zaposlenik` INT NOT NULL,
  PRIMARY KEY (`idotklonjeni_kvar`),
  INDEX `fk_otklonjeni_kvarovi_kvar1_idx` (`otklonjeni_kvar_kvar` ASC) VISIBLE,
  INDEX `fk_otklonjeni_kvar_zaposlenik1_idx` (`otklonjeni_kvar_zaposlenik` ASC) VISIBLE,
  CONSTRAINT `fk_otklonjeni_kvarovi_kvar1`
    FOREIGN KEY (`otklonjeni_kvar_kvar`)
    REFERENCES `mydb`.`kvar` (`idkvar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otklonjeni_kvar_zaposlenik1`
    FOREIGN KEY (`otklonjeni_kvar_zaposlenik`)
    REFERENCES `mydb`.`zaposlenik` (`idzaposlenik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usluga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usluga` (
  `idusluga` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `cijena` DOUBLE NULL,
  PRIMARY KEY (`idusluga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`racun_usluga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`racun_usluga` (
  `racun_idracun` INT NOT NULL,
  `usluga_idusluga` INT NOT NULL,
  `kolicina` SMALLINT NOT NULL,
  PRIMARY KEY (`racun_idracun`, `usluga_idusluga`),
  INDEX `fk_racun_has_usluga_usluga1_idx` (`usluga_idusluga` ASC) VISIBLE,
  INDEX `fk_racun_has_usluga_racun1_idx` (`racun_idracun` ASC) VISIBLE,
  CONSTRAINT `fk_racun_has_usluga_racun1`
    FOREIGN KEY (`racun_idracun`)
    REFERENCES `mydb`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_racun_has_usluga_usluga1`
    FOREIGN KEY (`usluga_idusluga`)
    REFERENCES `mydb`.`usluga` (`idusluga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obracun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obracun` (
  `idobracun` INT NOT NULL AUTO_INCREMENT,
  `broj_odradenih_sati` INT NULL,
  `iznos_place` DOUBLE NULL,
  `zaposlenik_idzaposlenik` INT NOT NULL,
  `mjesecni_raspored_idmjesecni_raspored` INT NOT NULL,
  PRIMARY KEY (`idobracun`),
  INDEX `fk_obracun_zaposlenik1_idx` (`zaposlenik_idzaposlenik` ASC) VISIBLE,
  INDEX `fk_obracun_mjesecni_raspored1_idx` (`mjesecni_raspored_idmjesecni_raspored` ASC) VISIBLE,
  CONSTRAINT `fk_obracun_zaposlenik1`
    FOREIGN KEY (`zaposlenik_idzaposlenik`)
    REFERENCES `mydb`.`zaposlenik` (`idzaposlenik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obracun_mjesecni_raspored1`
    FOREIGN KEY (`mjesecni_raspored_idmjesecni_raspored`)
    REFERENCES `mydb`.`mjesecni_raspored` (`idmjesecni_raspored`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`smjena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`smjena` (
  `idsmjena` INT NOT NULL AUTO_INCREMENT,
  `vrsta_smjene` VARCHAR(45) NULL,
  `zaposlenik_idzaposlenik` INT NOT NULL,
  `mjesecni_raspored_idmjesecni_raspored` INT NOT NULL,
  PRIMARY KEY (`idsmjena`),
  INDEX `fk_smjena_zaposlenik1_idx` (`zaposlenik_idzaposlenik` ASC) VISIBLE,
  INDEX `fk_smjena_mjesecni_raspored1_idx` (`mjesecni_raspored_idmjesecni_raspored` ASC) VISIBLE,
  CONSTRAINT `fk_smjena_zaposlenik1`
    FOREIGN KEY (`zaposlenik_idzaposlenik`)
    REFERENCES `mydb`.`zaposlenik` (`idzaposlenik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_smjena_mjesecni_raspored1`
    FOREIGN KEY (`mjesecni_raspored_idmjesecni_raspored`)
    REFERENCES `mydb`.`mjesecni_raspored` (`idmjesecni_raspored`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
