//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scvzApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class kvar
    {
        public int idkvar { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> datum_prijave { get; set; }
        public int kvar_idsoba { get; set; }
        public int kvar__prijavio_idstudent { get; set; }
        public int kvar_zaprimio_idzaposlenik { get; set; }
        public string status_kvara { get; set; }
    
        public virtual soba soba { get; set; }
        public virtual student student { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
    }
}
