//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scvzApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public racun()
        {
            this.racun_usluga = new HashSet<racun_usluga>();
        }
    
        public int idracun { get; set; }
        public string datum_vrijeme_racuna { get; set; }
        public Nullable<double> ukupna_cijena { get; set; }
        public string nacin_placanja { get; set; }
        public Nullable<int> racun_student { get; set; }
        public int zaposlenik_idzaposlenik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun_usluga> racun_usluga { get; set; }
        public virtual student student { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
    }
}
