//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scvzApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scvzAppEntities : DbContext
    {
        public scvzAppEntities()
            : base("name=scvzAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fakultet> fakultet { get; set; }
        public virtual DbSet<kvar> kvar { get; set; }
        public virtual DbSet<mjesec> mjesec { get; set; }
        public virtual DbSet<obracun> obracun { get; set; }
        public virtual DbSet<racun> racun { get; set; }
        public virtual DbSet<racun_usluga> racun_usluga { get; set; }
        public virtual DbSet<soba> soba { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tip_zaposlenika> tip_zaposlenika { get; set; }
        public virtual DbSet<usluga> usluga { get; set; }
        public virtual DbSet<zaposlenik> zaposlenik { get; set; }
        public virtual DbSet<zupanija> zupanija { get; set; }
        public virtual DbSet<smjena> smjena { get; set; }
    }
}
